# .rubocop.yml

# Based article from Evil Martians
# https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard
# referenced in standard readme relating to use of Standard with Rubocop extensions
# https://github.com/testdouble/standard

# We want Exclude directives from different
# config files to get merged, not overwritten
inherit_mode:
  merge:
    - Exclude

require:
  # Performance cops are bundled with Standard
  - rubocop-performance
  # Standard's config uses this custom cop,
  # so it must be loaded
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop_rails.yml
  # - .rubocop_todo.yml
  - .rubocop_rspec.yml

AllCops:
  Exclude:
    - "spec/dummy/config/*"
    - "spec/dummy/config/environments/*"
    - "spec/dummy/db/schema.rb"
    - "spec/spec_helper.rb"
    - "bin/*"
